### ISSUE TITLE
Credit the Jekyll theme

### ISSUE THREAD

**Issue by sdruskat** [CfA-Library/citesoftware.org2#7]
- E.g., use a CITATION.cff file and list them in the references

**Comment by jspaaks** [comment]
```yaml
# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

--- 
abstract: "Source files for https://citesoftware.org"
authors: 
  - 
    affiliation: "Harvard Center for Astrophysics Wolbach Library"
    email: daniel.chivvis@cfa.harvard.edu
    family-names: Chivvis
    given-names: Daniel
    orcid: "https://orcid.org/0000-0001-6656-160X"
  - 
    affiliation: "German Aerospace Center"
    email: stephan.druskat@dlr.de
    family-names: Druskat
    given-names: Stephan
    orcid: "https://orcid.org/0000-0003-4925-7248"
  - 
    affiliation: "Netherlands eScience Center"
    email: j.spaaks@esciencecenter.nl
    family-names: Spaaks
    given-names: "Jurriaan H."
    orcid: "https://orcid.org/0000-0002-7064-4069"
cff-version: "1.2.0"
identifiers: 
  - 
    description: "Web page where the data is hosted"
    type: url
    value: "https://citesoftware.org"
keywords: 
  - "software citation"
  - credit
  - FAIR
license: CC-BY-3.0
message: "If you use this data, please cite it using the metadata from this file."
references: 
  - 
    authors: 
      - 
        alias: "https://github.com/andrewbanchich"
        family-names: Banchich
        given-names: Andrew
      - 
        name: "Forty - Jekyll Theme Contributors"
    keywords: 
      - html
      - jekyll
      - theme
      - static-site-generator
      - ruby-gem
      - jekyll-theme
      - static-site
    license: CC-BY-3.0
    title: "Forty - Jekyll Theme"
    type: data
    url: "https://github.com/andrewbanchich/forty-jekyll-theme"
repository-code: "https://github.com/CfA-Library/citesoftware.org"
title: citesoftware.org
type: dataset
```
